### ISSUE TITLE
Refactor: File Naming Conventions and Bracketing of Functions Across the Project

### ISSUE THREAD

**Issue by SanchieGuzman** [leonhard-leung/cs311-final-project-demo#1]
# Description
I have noticed that the file naming convention and the bracketing of functions in our project does not follow the recently created coding standards. Kindly standardize all the file names and functions to make it easier to understand.

### Coding Convention
Please refer to the document below for further guidance:
https://docs.google.com/document/d/1UmMADx0csIDU4VLxZMvrCdyU-8UTqVLhLT-pddNE7iA/edit?tab=t.0

If something's not clear, feel free to comment here.

**Comment by Stephen-Coloma** [comment]
This issue has been resolved already.
